/*-
 * WSDL stubs for:  http://dblp.l3s.de/WS/dblp.php?wsdl
 *   Generated by:  amaxwell
 *           Date:  Thu Mar 20 17:58:52 2008
 *        Emitter:  Objective-C
 */

#import "BDSKDBLPWebServices.h"

/*-
 *   Method Name:  BDSKDBLPAllJournalTitlesYear
 * Documentation:  <no documentation>
 */
@implementation BDSKDBLPAllJournalTitlesYear
- (void) setParameters:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_year
{
    CFTypeRef _paramValues[] = {    
        in_year,        
    };    
    NSString* _paramNames[] = {    
        @"year",        
    };    
    [super setParameters:1 values:(id*) _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"titleString"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    [NSException raise:BDSKUnimplementedException format:@"%@", [NSString stringWithFormat:@"%@ is not currently implemented by the DBLP service", [self class]]];
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp.php"            
                 methodName: @"all_journal_titles_year"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_journal_titles_year"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* BDSKDBLPAllJournalTitlesYear */


/*-
 *   Method Name:  BDSKDBLPAllPublicationsKeywordsYear
 * Documentation:  <no documentation>
 */
@implementation BDSKDBLPAllPublicationsKeywordsYear
- (void) setParameters:(NSString*) in_searchTerm in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear in_limit:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_limit
{
    CFTypeRef _paramValues[] = {    
        in_searchTerm,        
        in_startYear,        
        in_endYear,        
        in_limit,        
    };    
    NSString* _paramNames[] = {    
        @"searchTerm",        
        @"startYear",        
        @"endYear",        
        @"limit",        
    };    
    [super setParameters:4 values:(id*) _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"return"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp.php"            
                 methodName: @"all_publications_keywords_year"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_publications_keywords_year"           
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* BDSKDBLPAllPublicationsKeywordsYear */


/*-
 *   Method Name:  BDSKDBLPAllPublicationsAuthorYear
 * Documentation:  <no documentation>
 */
@implementation BDSKDBLPAllPublicationsAuthorYear
- (void) setParameters:(NSString*) in_firstName in_familyName:(NSString*) in_familyName in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear
{
    CFTypeRef _paramValues[] = {    
        in_firstName,        
        in_familyName,        
        in_startYear,        
        in_endYear,        
    };    
    NSString* _paramNames[] = {    
        @"firstName",        
        @"familyName",        
        @"startYear",        
        @"endYear",        
    };    
    [super setParameters:4 values:(id*) _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"return"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp.php"            
                 methodName: @"all_publications_author_year"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_publications_author_year"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* BDSKDBLPAllPublicationsAuthorYear */


/*-
 *   Method Name:  BDSKDBLPAllJournalTitles
 * Documentation:  <no documentation>
 */
@implementation BDSKDBLPAllJournalTitles
- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"return"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    [NSException raise:BDSKUnimplementedException format:@"%@", [NSString stringWithFormat:@"%@ is not currently implemented by the DBLP service", [self class]]];
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp.php"            
                 methodName: @"all_journal_titles"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_journal_titles"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* BDSKDBLPAllJournalTitles */


/*-
 *   Method Name:  BDSKDBLPPublicationData
 * Documentation:  <no documentation>
 */
@implementation BDSKDBLPPublicationData
- (void) setParameters:(NSString*) in_dblp_key
{
    id _paramValues[] = {    
        in_dblp_key,        
    };    
    NSString* _paramNames[] = {    
        @"dblp_key",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"return"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp.php"            
                 methodName: @"publication_data"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#publication_data"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* BDSKDBLPPublicationData */


/*-
 *   Method Name:  BDSKDBLPVenueTitle
 * Documentation:  <no documentation>
 */
@implementation BDSKDBLPVenueTitle
- (void) setParameters:(NSString*) in_dblp_key
{
    id _paramValues[] = {    
        in_dblp_key,        
    };    
    NSString* _paramNames[] = {    
        @"dblp_key",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"titleString"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp.php"            
                 methodName: @"venue_title"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#venue_title"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* BDSKDBLPVenueTitle */


/*-
 *   Method Name:  BDSKDBLPAllProceedingTitles
 * Documentation:  <no documentation>
 */
@implementation BDSKDBLPAllProceedingTitles
- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"return"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    [NSException raise:BDSKUnimplementedException format:@"%@", [NSString stringWithFormat:@"%@ is not currently implemented by the DBLP service", [self class]]];
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp.php"            
                 methodName: @"all_proceeding_titles"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_proceeding_titles"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* BDSKDBLPAllProceedingTitles */


/*-
 *   Method Name:  BDSKDBLPPublicationAuthors
 * Documentation:  <no documentation>
 */
@implementation BDSKDBLPPublicationAuthors
- (void) setParameters:(NSString*) in_dblp_key
{
    id _paramValues[] = {    
        in_dblp_key,        
    };    
    NSString* _paramNames[] = {    
        @"dblp_key",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"return"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp.php"            
                 methodName: @"publication_authors"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#publication_authors"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* BDSKDBLPPublicationAuthors */


/*-
 *   Method Name:  BDSKDBLPAllPublicationsVenueYear
 * Documentation:  <no documentation>
 */
@implementation BDSKDBLPAllPublicationsVenueYear
- (void) setParameters:(NSString*) in_dblp_key_frag in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear
{
    CFTypeRef _paramValues[] = {    
        in_dblp_key_frag,        
        in_startYear,        
        in_endYear,        
    };    
    NSString* _paramNames[] = {    
        @"dblp_key_frag",        
        @"startYear",        
        @"endYear",        
    };    
    [super setParameters:3 values:(id*) _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"return"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp.php"            
                 methodName: @"all_publications_venue_year"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_publications_venue_year"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* BDSKDBLPAllPublicationsVenueYear */



@implementation DBLPPlusPlusService

+ (id) BDSKDBLPAllJournalTitlesYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_year
{
    id result = NULL;    
    BDSKDBLPAllJournalTitlesYear* _invocation = [[BDSKDBLPAllJournalTitlesYear alloc] init];    
    [_invocation setParameters: in_year];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return [result autorelease];    
}


+ (id) BDSKDBLPAllPublicationsKeywordsYear:(NSString*) in_searchTerm in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear in_limit:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_limit
{
    id result = NULL;    
    BDSKDBLPAllPublicationsKeywordsYear* _invocation = [[BDSKDBLPAllPublicationsKeywordsYear alloc] init];    
    [_invocation setParameters: in_searchTerm in_startYear:in_startYear in_endYear:in_endYear in_limit:in_limit];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return [result autorelease];    
}


+ (id) BDSKDBLPAllPublicationsAuthorYear:(NSString*) in_firstName in_familyName:(NSString*) in_familyName in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear
{
    id result = NULL;    
    BDSKDBLPAllPublicationsAuthorYear* _invocation = [[BDSKDBLPAllPublicationsAuthorYear alloc] init];    
    [_invocation setParameters: in_firstName in_familyName:in_familyName in_startYear:in_startYear in_endYear:in_endYear];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return [result autorelease];    
}


+ (id) BDSKDBLPAllJournalTitles
{
    id result = NULL;    
    BDSKDBLPAllJournalTitles* _invocation = [[BDSKDBLPAllJournalTitles alloc] init];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return [result autorelease];    
}


+ (id) BDSKDBLPPublicationData:(NSString*) in_dblp_key
{
    id result = NULL;    
    BDSKDBLPPublicationData* _invocation = [[BDSKDBLPPublicationData alloc] init];    
    [_invocation setParameters: in_dblp_key];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return [result autorelease];    
}


+ (id) BDSKDBLPVenueTitle:(NSString*) in_dblp_key
{
    id result = NULL;    
    BDSKDBLPVenueTitle* _invocation = [[BDSKDBLPVenueTitle alloc] init];    
    [_invocation setParameters: in_dblp_key];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return [result autorelease];    
}


+ (id) BDSKDBLPAllProceedingTitles
{
    id result = NULL;    
    BDSKDBLPAllProceedingTitles* _invocation = [[BDSKDBLPAllProceedingTitles alloc] init];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return [result autorelease];    
}


+ (id) BDSKDBLPPublicationAuthors:(NSString*) in_dblp_key
{
    id result = NULL;    
    BDSKDBLPPublicationAuthors* _invocation = [[BDSKDBLPPublicationAuthors alloc] init];    
    [_invocation setParameters: in_dblp_key];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return [result autorelease];    
}


+ (id) BDSKDBLPAllPublicationsVenueYear:(NSString*) in_dblp_key_frag in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear
{
    id result = NULL;    
    BDSKDBLPAllPublicationsVenueYear* _invocation = [[BDSKDBLPAllPublicationsVenueYear alloc] init];    
    [_invocation setParameters: in_dblp_key_frag in_startYear:in_startYear in_endYear:in_endYear];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return [result autorelease];    
}



@end;


/*-
 * End of WSDL document at http://dblp.l3s.de/WS/dblp.php?wsdl
 */
