/*-
 * WSDL stubs for:  http://dblp.l3s.de/WS/dblp++.php?wsdl
 *   Generated by:  amaxwell
 *           Date:  Thu Mar 20 17:58:52 2008
 *        Emitter:  Objective-C
 */

#ifndef __BDSKDBLPWebServices__
#define __BDSKDBLPWebServices__

#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>
#import "WSGeneratedObj.h"

/*-
 *   Web Service:  DBLPPlusPlusService
 * Documentation:  <not documented>
 */
/*-
 *   Method Name:  BDSKDBLPAllJournalTitlesYear
 * Documentation:  <no documentation>
 */

@interface BDSKDBLPAllJournalTitlesYear : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_year;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* BDSKDBLPAllJournalTitlesYear */


/*-
 *   Method Name:  BDSKDBLPAllPublicationsKeywordsYear
 * Documentation:  <no documentation>
 */

@interface BDSKDBLPAllPublicationsKeywordsYear : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_searchTerm in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear in_limit:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_limit;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* BDSKDBLPAllPublicationsKeywordsYear */


/*-
 *   Method Name:  BDSKDBLPAllPublicationsAuthorYear
 * Documentation:  <no documentation>
 */

@interface BDSKDBLPAllPublicationsAuthorYear : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_firstName in_familyName:(NSString*) in_familyName in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* BDSKDBLPAllPublicationsAuthorYear */


/*-
 *   Method Name:  BDSKDBLPAllJournalTitles
 * Documentation:  <no documentation>
 */

@interface BDSKDBLPAllJournalTitles : WSGeneratedObj

// No parameters for this method

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* BDSKDBLPAllJournalTitles */


/*-
 *   Method Name:  BDSKDBLPPublicationData
 * Documentation:  <no documentation>
 */

@interface BDSKDBLPPublicationData : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_dblp_key;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* BDSKDBLPPublicationData */


/*-
 *   Method Name:  BDSKDBLPVenueTitle
 * Documentation:  <no documentation>
 */

@interface BDSKDBLPVenueTitle : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_dblp_key;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* BDSKDBLPVenueTitle */


/*-
 *   Method Name:  BDSKDBLPAllProceedingTitles
 * Documentation:  <no documentation>
 */

@interface BDSKDBLPAllProceedingTitles : WSGeneratedObj

// No parameters for this method

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* BDSKDBLPAllProceedingTitles */


/*-
 *   Method Name:  BDSKDBLPPublicationAuthors
 * Documentation:  <no documentation>
 */

@interface BDSKDBLPPublicationAuthors : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_dblp_key;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* BDSKDBLPPublicationAuthors */


/*-
 *   Method Name:  BDSKDBLPAllPublicationsVenueYear
 * Documentation:  <no documentation>
 */

@interface BDSKDBLPAllPublicationsVenueYear : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_dblp_key_frag in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* BDSKDBLPAllPublicationsVenueYear */


/*-
 * Web Service:  DBLPPlusPlusService
 */
@interface DBLPPlusPlusService : NSObject 

+ (id) BDSKDBLPAllJournalTitlesYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_year;
+ (id) BDSKDBLPAllPublicationsKeywordsYear:(NSString*) in_searchTerm in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear in_limit:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_limit;
+ (id) BDSKDBLPAllPublicationsAuthorYear:(NSString*) in_firstName in_familyName:(NSString*) in_familyName in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear;
+ (id) BDSKDBLPAllJournalTitles;
+ (id) BDSKDBLPPublicationData:(NSString*) in_dblp_key;
+ (id) BDSKDBLPVenueTitle:(NSString*) in_dblp_key;
+ (id) BDSKDBLPAllProceedingTitles;
+ (id) BDSKDBLPPublicationAuthors:(NSString*) in_dblp_key;
+ (id) BDSKDBLPAllPublicationsVenueYear:(NSString*) in_dblp_key_frag in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear;

@end;


#endif /* __BDSKDBLPWebServices__ */
/*-
 * End of WSDL document at http://dblp.l3s.de/WS/dblp++.php?wsdl
 */
