#!/usr/bin/perl -w

print "*******************************\n";
print "Welcome to BibDesk development.\n";
print "This script will get the stuff you need from cvs to build bibdesk.\n";
print "Developers should set SF_USERNAME to use ssh access\n";

$SFNAME=getSFName();

if ($SFNAME ne "") {
    prepdev();
} else {
    prepanon();
}
getsources();

print "\n****************************\n";                     
print "getBibdeskCVS done.  Now you should open\n";
print "bibdesk/Bibdesk.pbproj and commence the build.\n";

sub getSFName {
  if (defined $ENV{'SF_USERNAME'} ) { 
	return $ENV{'SF_USERNAME'};
  } else {
      print "Are you a developer (y/n)? ";
      $DEV = <STDIN>;
      if ( $DEV eq "n\n" ) {
	  return "";
      } else {
         print "What is your sourceforge username (setenv SF_USERNAME for a default)?  ";
         $SFNAME = <STDIN>;
	 return($SFNAME);
      }
  }
}

sub prepanon {
  $CVS_METHOD = "pserver";
  $SFNAME = "anonymous";
  $LOGIN = "cvs -z3 -d:$CVS_METHOD:$SFNAME\@cvs.sourceforge.net:/cvsroot/bibdesk login";
  print "$LOGIN\n";
  print "Password is empty--just hit return when asked for a password\n";
  system $LOGIN;
}

sub prepdev {
  $ENV{'CVS_RSH'} = 'ssh';
  $CVS_METHOD = "ext";
}

sub getsources {
   $GETMAIN = "cvs -z3 -d:$CVS_METHOD:$SFNAME\@cvs.sourceforge.net:/cvsroot/bibdesk co bibdesk";
   print "$GETMAIN\n";
   system $GETMAIN;

   $GETVENDOR = "cvs -z3 -d:$CVS_METHOD:$SFNAME\@cvs.sourceforge.net:/cvsroot/bibdesk co bibdesk_vendorsrc";
   print "$GETVENDOR\n";
   system $GETVENDOR;
}
