// _BDSKSearchGroupSheet_EOArchive_French.java
// Generated by EnterpriseObjects palette at Wednesday, May 2, 2007 14:17:33  US/Central

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _BDSKSearchGroupSheet_EOArchive_French extends com.webobjects.eoapplication.EOArchive {
    BDSKCollapsibleView _nsCustomView0;
    IBHelpConnector _iBHelpConnector0, _iBHelpConnector1, _iBHelpConnector10, _iBHelpConnector11, _iBHelpConnector12, _iBHelpConnector13, _iBHelpConnector14, _iBHelpConnector2, _iBHelpConnector3, _iBHelpConnector4, _iBHelpConnector5, _iBHelpConnector6, _iBHelpConnector7, _iBHelpConnector8, _iBHelpConnector9;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField12, _nsTextField13, _nsTextField14, _nsTextField15, _nsTextField16, _nsTextField17, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2, _nsBox3, _nsBox4, _nsBox5;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2, _nsButton3, _nsButton4, _nsButton5;
    javax.swing.JCheckBox _nsButton6;
    javax.swing.JComboBox _nsComboBox0, _popup0, _popup1;
    javax.swing.JPanel _nsView0;
    javax.swing.JPasswordField _nsTextField18;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1;

    public _BDSKSearchGroupSheet_EOArchive_French(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField17 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField23");
        _nsTextField16 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField211");
        _iBHelpConnector14 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector13 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "revealButton")) != null)) {
            _nsButton5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton5");
        } else {
            _nsButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton("Bouton"), "NSButton2");
        }

        _nsTextField15 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2111");
        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox12");
        _iBHelpConnector12 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "removeDiacriticsButton")) != null)) {
            _nsButton6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton6");
        } else {
            _nsButton6 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Supprimer les signes diacritiques"), "NSButton4");
        }

        _nsTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21322");
        _iBHelpConnector11 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "encodingComboBox")) != null)) {
            _nsComboBox0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsComboBox0");
        } else {
            _nsComboBox0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSComboBox");
        }

        _nsTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21321");
        _iBHelpConnector10 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "syntaxPopup")) != null)) {
            _popup1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup1");
        } else {
            _popup1 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton1");
        }

        _nsTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2132");
        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox11");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField214");
        _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2131");
        _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField213");
        _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField212");
        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField22");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "serverView")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (BDSKCollapsibleView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (BDSKCollapsibleView)_registered(new BDSKCollapsibleView(), "View");
        }

        _iBHelpConnector9 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "typeMatrix.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField5");
        } else {
            _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField12");
        }

        _iBHelpConnector8 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "nameField.nextFocusableComponent")) != null)) {
            _nsTextField4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField4");
        } else {
            _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        }

        _iBHelpConnector7 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector6 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector5 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector4 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "addressField.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsButton4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton4");
        } else {
            _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("Ajouter"), "NSButton2111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "addressField.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField18 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JPasswordField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField18");
        } else {
            _nsTextField18 = (javax.swing.JPasswordField)_registered(new javax.swing.JPasswordField(), "NSTextField4");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "addressField.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField3");
        } else {
            _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField3");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "addressField.nextFocusableComponent")) != null)) {
            _nsTextField2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField2");
        } else {
            _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "databaseField.nextFocusableComponent")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        _iBHelpConnector3 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector2 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector1 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "editButton")) != null)) {
            _nsButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton3");
        } else {
            _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("\u00c9dition"), "NSButton21");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "editButton.nextFocusableComponent")) != null)) {
            _nsButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton2");
        } else {
            _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Tout r\u00e9initialiser"), "NSButton2");
        }

        _iBHelpConnector0 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("OK"), "NSButton");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Annuler"), "NSButton1");
        _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Z39.50"), "");
        _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Entrez"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "typeMatrix")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 2, 4, 2), "NSMatrix1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "typeMatrix.nextFocusableComponent")) != null)) {
            _popup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup0");
        } else {
            _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "toggle", _nsButton5), ""));

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _connect(_owner(), _nsButton5, "revealButton");
        }

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _connect(_owner(), _nsButton6, "removeDiacriticsButton");
        }

        if (_replacedObjects.objectForKey("_nsComboBox0") == null) {
            _connect(_owner(), _nsComboBox0, "encodingComboBox");
        }

        if (_replacedObjects.objectForKey("_nsComboBox0") == null) {
            _nsComboBox0.setModel(new javax.swing.DefaultComboBoxModel());
            _nsComboBox0.addItem("utf-8");
            _nsComboBox0.addItem("iso-8859-1");
            _nsComboBox0.addItem("marc-8");
            _nsComboBox0.addItem("ansel");
            _nsComboBox0.setSelectedIndex(0);
        }

        if (_replacedObjects.objectForKey("_popup1") == null) {
            _connect(_owner(), _popup1, "syntaxPopup");
        }

        _popup1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectSyntax", _popup1), ""));

        if (_replacedObjects.objectForKey("_popup1") == null) {
            _popup1.setModel(new javax.swing.DefaultComboBoxModel());
            _popup1.addItem("Par d\u00e9faut");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "serverView");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_owner(), _nsTextField5, "nameField");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_owner(), _nsTextField4, "databaseField");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_owner(), _nsTextField2, "portField");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_owner(), _nsTextField3, "userField");
        }

        if (_replacedObjects.objectForKey("_nsTextField18") == null) {
            _connect(_owner(), _nsTextField18, "passwordField");
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _connect(_owner(), _nsButton4, "addRemoveButton");
        }

        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "addRemoveServer", _nsButton4), ""));

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "addressField");
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_owner(), _nsButton3, "editButton");
        }

        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "editServer", _nsButton3), ""));
        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "resetServers", _nsButton2), ""));
        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "dismiss", _nsButton1), ""));
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "dismiss", _nsButton0), ""));
        _jRadioButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectServerType", _jRadioButton0), ""));
        _jRadioButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectServerType", _jRadioButton1), ""));

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "typeMatrix");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _connect(_owner(), _popup0, "serverPopup");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        _popup0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectPredefinedServer", _popup0), ""));

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _popup0.setModel(new javax.swing.DefaultComboBoxModel());
            _popup0.addItem("Objet1");
            _popup0.addItem("Objet2");
            _popup0.addItem("Objet3");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField17, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField17.setEditable(false);
        _nsTextField17.setOpaque(false);
        _nsTextField17.setText("Type :");
        _nsTextField17.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField17.setSelectable(false);
        _nsTextField17.setEnabled(true);
        _nsTextField17.setBorder(null);
        _setFontForComponent(_nsTextField16, "Lucida Grande", 13, Font.PLAIN + Font.BOLD);
        _nsTextField16.setEditable(false);
        _nsTextField16.setOpaque(false);
        _nsTextField16.setText("R\u00e9glage de groupe de recherche");
        _nsTextField16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField16.setSelectable(false);
        _nsTextField16.setEnabled(true);
        _nsTextField16.setBorder(null);

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _setFontForComponent(_nsButton5, "Lucida Grande", 13, Font.PLAIN);
            _nsButton5.setMargin(new Insets(0, 2, 0, 2));
        }

        _setFontForComponent(_nsTextField15, "Lucida Grande", 11, Font.PLAIN + Font.BOLD);
        _nsTextField15.setEditable(false);
        _nsTextField15.setOpaque(false);
        _nsTextField15.setText("R\u00e9glages du serveur");
        _nsTextField15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField15.setSelectable(false);
        _nsTextField15.setEnabled(true);
        _nsTextField15.setBorder(null);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(125, 1);
        _nsBox5.setLocation(2, 2);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _setFontForComponent(_nsButton6, "Lucida Grande", 11, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField14, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField14.setEditable(false);
        _nsTextField14.setOpaque(false);
        _nsTextField14.setText("Encodage :");
        _nsTextField14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField14.setSelectable(false);
        _nsTextField14.setEnabled(true);
        _nsTextField14.setBorder(null);
        _setFontForComponent(_nsTextField13, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField13.setEditable(false);
        _nsTextField13.setOpaque(false);
        _nsTextField13.setText("Par d\u00e9faut :");
        _nsTextField13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField13.setSelectable(false);
        _nsTextField13.setEnabled(true);
        _nsTextField13.setBorder(null);

        if (_replacedObjects.objectForKey("_popup1") == null) {
            _setFontForComponent(_popup1, "Lucida Grande", 11, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField12, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField12.setEditable(false);
        _nsTextField12.setOpaque(false);
        _nsTextField12.setText("Syntaxe :");
        _nsTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField12.setSelectable(false);
        _nsTextField12.setEnabled(true);
        _nsTextField12.setBorder(null);
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(125, 1);
        _nsBox3.setLocation(2, 2);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(125, 1);
        _nsBox1.setLocation(2, 2);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField11, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField11.setEditable(false);
        _nsTextField11.setOpaque(false);
        _nsTextField11.setText("Nom :");
        _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField11.setSelectable(false);
        _nsTextField11.setEnabled(true);
        _nsTextField11.setBorder(null);
        _setFontForComponent(_nsTextField10, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField10.setEditable(false);
        _nsTextField10.setOpaque(false);
        _nsTextField10.setText("Mot de passe\u00a0:");
        _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField10.setSelectable(false);
        _nsTextField10.setEnabled(true);
        _nsTextField10.setBorder(null);
        _setFontForComponent(_nsTextField9, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField9.setEditable(false);
        _nsTextField9.setOpaque(false);
        _nsTextField9.setText("Identifiant :");
        _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField9.setSelectable(false);
        _nsTextField9.setEnabled(true);
        _nsTextField9.setBorder(null);
        _setFontForComponent(_nsTextField8, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField8.setEditable(false);
        _nsTextField8.setOpaque(false);
        _nsTextField8.setText("Base de donn\u00e9es :");
        _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField8.setSelectable(false);
        _nsTextField8.setEnabled(true);
        _nsTextField8.setBorder(null);
        _setFontForComponent(_nsTextField7, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("Port :");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        _setFontForComponent(_nsTextField6, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Adresse :");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsTextField6.setSize(54, 14);
            _nsTextField6.setLocation(50, 132);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField6);
            _nsTextField2.setSize(36, 19);
            _nsTextField2.setLocation(327, 129);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField2);
            _nsTextField7.setSize(29, 14);
            _nsTextField7.setLocation(293, 132);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField7);
            _nsTextField1.setSize(181, 19);
            _nsTextField1.setLocation(107, 129);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField1);
            _nsTextField8.setSize(101, 14);
            _nsTextField8.setLocation(3, 105);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField8);
            _nsTextField4.setSize(256, 19);
            _nsTextField4.setLocation(107, 102);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField4);
            _nsTextField3.setSize(94, 19);
            _nsTextField3.setLocation(107, 156);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField3);
            _nsTextField9.setSize(66, 14);
            _nsTextField9.setLocation(38, 159);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField9);
            _nsTextField10.setSize(58, 14);
            _nsTextField10.setLocation(206, 159);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField10);
            _nsTextField18.setSize(94, 19);
            _nsTextField18.setLocation(269, 156);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField18, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField18);
            _nsTextField11.setSize(37, 14);
            _nsTextField11.setLocation(67, 78);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField11);
            _nsTextField5.setSize(256, 19);
            _nsTextField5.setLocation(107, 75);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField5);
            _nsButton2.setSize(107, 22);
            _nsButton2.setLocation(249, 17);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsButton2);
            _nsButton3.setSize(66, 22);
            _nsButton3.setLocation(178, 17);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsButton3);
            _nsButton4.setSize(66, 22);
            _nsButton4.setLocation(107, 17);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsButton4);
            _nsBox0.setSize(348, 5);
            _nsBox0.setLocation(12, 42);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsBox0);
            _nsBox2.setSize(348, 5);
            _nsBox2.setLocation(12, 231);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsBox2);
            _nsTextField12.setSize(53, 14);
            _nsTextField12.setLocation(51, 185);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField12, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField12);
            _popup1.setSize(93, 22);
            _popup1.setLocation(108, 182);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_popup1, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_popup1);
            _nsTextField13.setSize(66, 14);
            _nsTextField13.setLocation(38, 21);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField13, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField13);
            _nsComboBox0.setSize(97, 22);
            _nsComboBox0.setLocation(107, 207);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsComboBox0, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsComboBox0);
            _nsTextField14.setSize(63, 14);
            _nsTextField14.setLocation(41, 211);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField14, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField14);
            _nsButton6.setSize(134, 28);
            _nsButton6.setLocation(230, 199);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsButton6);
            _nsBox4.setSize(348, 5);
            _nsBox4.setLocation(12, 8);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsBox4);
            _nsTextField15.setSize(120, 14);
            _nsTextField15.setLocation(18, 53);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField15, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField15);
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _connect(_popup0, _nsTextField5, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _setFontForComponent(_nsTextField5, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField5.setEditable(true);
            _nsTextField5.setOpaque(true);
            _nsTextField5.setText("");
            _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField5.setSelectable(true);
            _nsTextField5.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_nsTextField5, _nsTextField4, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _setFontForComponent(_nsTextField4, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField4.setEditable(true);
            _nsTextField4.setOpaque(true);
            _nsTextField4.setText("");
            _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField4.setSelectable(true);
            _nsTextField4.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_nsTextField4, _nsTextField1, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _setFontForComponent(_nsButton4, "Lucida Grande", 11, Font.PLAIN);
            _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsTextField18") == null) {
            _connect(_nsTextField18, _nsButton4, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField18") == null) {
            _setFontForComponent(_nsTextField18, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField18.setEditable(true);
            _nsTextField18.setOpaque(true);
            _nsTextField18.setText("");
            _nsTextField18.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField18.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_nsTextField3, _nsTextField18, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _setFontForComponent(_nsTextField3, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField3.setEditable(true);
            _nsTextField3.setOpaque(true);
            _nsTextField3.setText("");
            _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField3.setSelectable(true);
            _nsTextField3.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_nsTextField2, _nsTextField3, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _setFontForComponent(_nsTextField2, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField2.setEditable(true);
            _nsTextField2.setOpaque(true);
            _nsTextField2.setText("");
            _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField2.setSelectable(true);
            _nsTextField2.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_nsTextField1, _nsTextField2, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField1.setEditable(true);
            _nsTextField1.setOpaque(true);
            _nsTextField1.setText("");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _setFontForComponent(_nsButton3, "Lucida Grande", 11, Font.PLAIN);
            _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_nsButton3, _nsButton2, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _setFontForComponent(_nsButton2, "Lucida Grande", 11, Font.PLAIN);
            _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _connect(_nsButton2, _nsButton1, "nextFocusableComponent");
        }

        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _connect(_nsButton1, _nsButton0, "nextFocusableComponent");
        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _connect(_nsButton0, _nsMatrix0, "nextFocusableComponent");

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_nsMatrix0, _popup0, "nextFocusableComponent");
        }

        _setFontForComponent(_jRadioButton1, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton0, "Lucida Grande", 13, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _jRadioButton0.setSize(67, 18);
            _jRadioButton0.setLocation(0, 0);
            _nsMatrix0.add(_jRadioButton0);
            _jRadioButton1.setSize(67, 18);
            _jRadioButton1.setLocation(71, 0);
            _nsMatrix0.add(_jRadioButton1);
            _setFontForComponent(_nsMatrix0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _setFontForComponent(_popup0, "Lucida Grande", 13, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Serveur :\n");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(60, 34);
        _nsTextField0.setLocation(28, 64);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField0);
        _popup0.setSize(224, 26);
        _popup0.setLocation(91, 61);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsView0.add(_popup0);
        _nsButton1.setSize(75, 26);
        _nsButton1.setLocation(274, 345);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _nsButton0.setSize(75, 26);
        _nsButton0.setLocation(192, 345);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _nsTextField16.setSize(220, 17);
        _nsTextField16.setLocation(12, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField16, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField16);
        _nsMatrix0.setSize(138, 18);
        _nsMatrix0.setLocation(87, 39);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsMatrix0);
        _nsTextField17.setSize(43, 17);
        _nsTextField17.setLocation(45, 39);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField17, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField17);
        _nsCustomView0.setSize(372, 244);
        _nsCustomView0.setLocation(-7, 93);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_nsCustomView0);
        _nsButton5.setSize(27, 25);
        _nsButton5.setLocation(320, 62);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsButton5);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(358, 381);
            _eoFrame0.setTitle("Fen\u00eatre");
            _eoFrame0.setLocation(159, 423);
            _eoFrame0.setSize(358, 381);
        }
    }
}
