// _Previewer_EOArchive_French.java
// Generated by EnterpriseObjects palette at Wednesday, May 2, 2007 14:15:33  US/Central

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _Previewer_EOArchive_French extends com.webobjects.eoapplication.EOArchive {
    BDSKCollapsibleView _nsCustomView0;
    IBHelpConnector _iBHelpConnector0;
    NSApplication _nsApplication0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1;
    com.webobjects.eointerface.swing.EOImageView _nsImageView0;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0, _nsTextView1;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0;
    com.webobjects.eointerface.swing.EOView _nsCustomView1, _nsCustomView2, _nsProgressIndicator0, _nsView0, _nsView1, _nsView2, _pDFView0;
    javax.swing.JPanel _nsView3, _nsView4;
    javax.swing.JTabbedPane _nsTabView0;

    public _Previewer_EOArchive_French(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsApplication0 = (NSApplication)_registered(new NSApplication(), "Application");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame1");
        } else {
            _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Panel");
        }

        _nsView4 = (JPanel)_eoFrame1.getContentPane();
        _iBHelpConnector0 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "warningImageView")) != null)) {
            _nsImageView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOImageView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsImageView0");
        } else {
            _nsImageView0 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "Image View (BDSKSmallCautionIcon)");
        }

        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "Static Text (TeX preview generation failed)");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "warningView")) != null)) {
            _nsCustomView2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView2");
        } else {
            _nsCustomView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "Custom View-1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "logView")) != null)) {
            _nsTextView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextArea)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextView1");
        } else {
            _nsTextView1 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "Zoomable Text View-1");
        }

        _nsView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View-2");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "rtfPreviewView")) != null)) {
            _nsTextView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextArea)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextView0");
        } else {
            _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "Zoomable Text View");
        }

        _nsView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View-1");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "pdfView")) != null)) {
            _pDFView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_pDFView0");
        } else {
            _pDFView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "Zoomable P D F View");
        }

        _nsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tabView")) != null)) {
            _nsTabView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JTabbedPane)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTabView0");
        } else {
            _nsTabView0 = (javax.swing.JTabbedPane)_registered(new javax.swing.JTabbedPane(), "Left Tab View (PDF, Text, Log)");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "progressIndicator")) != null)) {
            _nsProgressIndicator0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsProgressIndicator0");
        } else {
            _nsProgressIndicator0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "11");
        }

        _nsCustomView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "Custom View");
        _nsCustomView0 = (BDSKCollapsibleView)_registered(new BDSKCollapsibleView(), "Collapsible View");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "progressOverlay")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "ProgressOverlay");
        }

        _nsView3 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _connect(_eoFrame1, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _connect(_owner(), _eoFrame1, "window");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "progressOverlay");
        }

        if (_replacedObjects.objectForKey("_nsImageView0") == null) {
            _connect(_owner(), _nsImageView0, "warningImageView");
        }

        if (_replacedObjects.objectForKey("_nsCustomView2") == null) {
            _connect(_owner(), _nsCustomView2, "warningView");
        }

        if (_replacedObjects.objectForKey("_nsTabView0") == null) {
            _connect(_nsTabView0, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextView1") == null) {
            _connect(_owner(), _nsTextView1, "logView");
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _connect(_owner(), _nsTextView0, "rtfPreviewView");
        }

        if (_replacedObjects.objectForKey("_pDFView0") == null) {
            _connect(_owner(), _pDFView0, "pdfView");
        }

        if (_replacedObjects.objectForKey("_nsTabView0") == null) {
            _connect(_owner(), _nsTabView0, "tabView");
        }

        if (_replacedObjects.objectForKey("_nsProgressIndicator0") == null) {
            _connect(_owner(), _nsProgressIndicator0, "progressIndicator");
        }
    }

    protected void _init() {
        super._init();
        if (!(_nsView4.getLayout() instanceof EOViewLayout)) { _nsView4.setLayout(new EOViewLayout()); }
        _nsTabView0.setSize(549, 145);
        _nsTabView0.setLocation(1, -16);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTabView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView4.add(_nsTabView0);

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _nsView4.setSize(538, 110);
            _eoFrame1.setTitle("Aper\u00e7u LaTeX");
            _eoFrame1.setLocation(171, 334);
            _eoFrame1.setSize(538, 110);
        }

        _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("\u00c9chec de cr\u00e9ation de l'aper\u00e7u TeX");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);

        if (_replacedObjects.objectForKey("_nsCustomView2") == null) {
            if (!(_nsCustomView2.getLayout() instanceof EOViewLayout)) { _nsCustomView2.setLayout(new EOViewLayout()); }
            _nsTextField0.setSize(189, 14);
            _nsTextField0.setLocation(22, 5);
            ((EOViewLayout)_nsCustomView2.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
            _nsCustomView2.add(_nsTextField0);
            _nsImageView0.setSize(16, 16);
            _nsImageView0.setLocation(4, 4);
            ((EOViewLayout)_nsCustomView2.getLayout()).setAutosizingMask(_nsImageView0, EOViewLayout.MinYMargin);
            _nsCustomView2.add(_nsImageView0);
        }

        if (_replacedObjects.objectForKey("_nsTextView1") == null) {
            _nsTextView1.setEditable(false);
            _nsTextView1.setOpaque(true);
            _nsTextView1.setText("");
        }

        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsTextView1.setSize(530, 123);
        _nsTextView1.setLocation(0, 5);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextView1, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView2.add(_nsTextView1);

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _nsTextView0.setEditable(false);
            _nsTextView0.setOpaque(true);
            _nsTextView0.setText("");
        }

        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsTextView0.setSize(530, 123);
        _nsTextView0.setLocation(0, 5);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView1.add(_nsTextView0);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _pDFView0.setSize(530, 123);
        _pDFView0.setLocation(0, 5);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_pDFView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_pDFView0);

        if (_replacedObjects.objectForKey("_nsTabView0") == null) {
            _nsTabView0.addTab("PDF", _nsView0);
            _nsTabView0.addTab("Texte", _nsView1);
            _nsTabView0.addTab("Journal", _nsView2);
        }

        if (!(_nsCustomView1.getLayout() instanceof EOViewLayout)) { _nsCustomView1.setLayout(new EOViewLayout()); }
        _nsProgressIndicator0.setSize(32, 32);
        _nsProgressIndicator0.setLocation(90, 30);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsProgressIndicator0, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin | EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsProgressIndicator0);
        _nsCustomView2.setSize(181, 20);
        _nsCustomView2.setLocation(0, 2);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsCustomView2, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsCustomView1.add(_nsCustomView2);
        if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
        _nsCustomView1.setSize(213, 92);
        _nsCustomView1.setLocation(0, 0);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsCustomView1, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsCustomView0.add(_nsCustomView1);
        if (!(_nsView3.getLayout() instanceof EOViewLayout)) { _nsView3.setLayout(new EOViewLayout()); }
        _nsCustomView0.setSize(213, 107);
        _nsCustomView0.setLocation(-7, -6);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView3.add(_nsCustomView0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView3.setSize(199, 95);
            _eoFrame0.setTitle("Superposition");
            _eoFrame0.setLocation(243, 503);
            _eoFrame0.setSize(199, 95);
        }
    }
}
